(define (problem clamidia)
 (:domain MST)
 (:requirements :typing)
 (:objects BJN BNN BRN VJ NV RV NJ NN RN BLJ BLN BLR BJS BNS BRS - node
	pince - claw)
 (:init (link BJN BNN) 
	(link BNN BJN)
	(link BNN BRN)
	(link BRN BNN)
	(link BRN RV) 
	(link RV BRN) 
	(link RV RN) 
	(link RN RV) 
	(link RN BLR) 
	(link BLR RN) 
	(link BLR BRS) 
	(link BRS BLR) 
	(link BRS BNS) 
	(link BNS BRS) 
	(link BNS BJS) 
	(link BJS BNS) 
	(link BJS BLJ) 
	(link BLJ BJS) 
	(link BLJ NJ) 
	(link NJ BLJ) 
	(link NJ VJ) 
	(link VJ NJ)
	(link VJ BJN)
	(link BJN VJ) 
	(link BNN NV) 
	(link NV BNN) 
	(link NV NN) 
	(link NN NV) 
	(link NN BLN) 
	(link BLN NN) 
	(link BLN BNS) 
	(link BNS BLN) 
	(link VJ NV) 
	(link NV VJ) 
	(link NV RV) 
	(link RV NV) 
	(link NJ NN) 
	(link NN NJ) 
	(link NN RN) 
	(link RN NN) 
	(link BLJ BLN) 
	(link BLN BLJ) 
	(link BLN BLR)
	(link BLR BLN)
	(at BNS)
	(opened pince)
)
(:goal (and (at NN) (closed pince))
)
)


 

